### ISSUE TITLE
[Proposal] SEO

### ISSUE THREAD

**Issue by ktnorm** [Skooldio/dev.share#10]
### Title of your topic
ss - ee - oh

### Topic description
basic technical SEO and SEO in general. 

### Presenter(s)
aomm

### Duration
15 mins

### Do you need time to prepare this talk?
nope, already prepared.. i guess..

**Comment by pakaponk** [comment]
@ktnorm  Would you like to share this week?

**Comment by ktnorm** [comment]
> @ktnorm Would you like to share this week?

Yup! told you it's gonna be before the end of this year 😅

**Comment by pakaponk** [comment]
Thanks for sharing it with us 🙂

Looking forward to the next one 😃
