### ISSUE TITLE
[Proposal] Tip&Trick to reduce docker container size

### ISSUE THREAD

**Issue by phuttipong** [Skooldio/dev.share#2]
### Title of your topic
Tip&Trick to reduce docker container size

### Topic description
Tip and trick that we use to we recently used to reduce our API docker container size. 

### Presenter(s)
Pog.

### Duration
15 mins.

### Do you need time to prepare this talk?
No

**Comment by pakaponk** [comment]
@phuttipong Forget to replace the template?

**Comment by phuttipong** [comment]
Because build time increasing overtime, see [this PR](https://bitbucket.org/skooldio/lsp-api/pull-requests/163/increase-cloudbuild-timeout-to-1000s/diff)

So I check CI build log and notice that docker build step is the most time-consuming.
<img width="356" alt="Screen Shot 2563-07-15 at 12 02 57" src="https://user-images.githubusercontent.com/10227828/87505580-6712d100-c693-11ea-8e27-9cb3d17b707e.png">

Then I did 2 things to reduce docker build processing time by 30%. 
1. use .DOCKERIGNORE to ignore unneeded files.
2. reuse devDependencies to build production dependencies
<img width="915" alt="Screen Shot 2563-07-15 at 12 56 31" src="https://user-images.githubusercontent.com/10227828/87508941-abee3600-c69a-11ea-90f5-7c581e5e89b3.png">


see change in [this PR](https://bitbucket.org/skooldio/lsp-api/pull-requests/164/chore-config-cloud-build/diff)

[dockerfile reference](https://docs.docker.com/engine/reference/builder/)

**Comment by phuttipong** [comment]
@pakaponk suggest that docker can build docker-image in parallel mode.

I found out that 
- docker-compose can build in parallel, see this [blog](https://medium.com/schkn/parallelize-your-docker-compose-build-8ac653e3e596)
- but docker build not have `--parallel` option, see [docker reference](https://docs.docker.com/engine/reference/commandline/build/)
