### ISSUE TITLE
[Proposal] What is Intl API in javascript and How to use it 

### ISSUE THREAD

**Issue by icesernia** [Skooldio/dev.share#7]
### Title of your topic
What is Intl API in javascript and How to use it 

### Topic description
I'll be sharing few topic
 - What is Intl ?
 - How to use Intl ?
 - Future of Intl 

### Presenter(s)
Icezy

### Duration
20 - 30 mins

### Do you need time to prepare this talk?
No

**Comment by pakaponk** [comment]
Thanks for submitting the talk.

Great jobs delivering it today. 👍
